version: "3"
services:
    # react frontend management ui for development
    management:
        build:
            context: .
            dockerfile: dockerfile
        stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
        container_name: management_dev
        expose:
            - "4000"
        volumes:
            - ./frontend/src:/usr/src/app/src

networks:
    default:
        external:
            name: gateway_network
