version: "3"
services:
    management:
        build:
            context: .
            dockerfile: dockerfile
        container_name: management_ui
        volumes:
            - blog_content:/dist

networks:
    default:
        external:
            name: gateway_network

# Using `external: true` causes docker to complain if the volume does not exist
volumes:
    blog_content:
        external: true
